sudo: required
services:
    - docker

before_install:
    - docker build -t anupbisht/react-test -f ./client/Dockerfile.dev ./client
    
scripts:
    -  docker run -e CI=true anupbisht/react-test npm test -- --coverage
    
after_success:
    - docker build -t anupbisht/multi-client  ./client
    - docker build -t anupbisht/multi-nginx ./nginx
    - docker build -t anupbisht/multi-server  ./server
    - docker build -t anupbisht/multi-worker  ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push anupbisht/multi-client 
    - docker push anupbisht/multi-nginx 
    - docker push anupbisht/multi-server 
    - docker push anupbisht/multi-worker 

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env-1"
    bucket_name: "elasticbeanstalk-us-east-2-871316717499"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY